/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __eurecar_dw_lane_detection_hpp__
#define __eurecar_dw_lane_detection_hpp__

#include <lcm/lcm_coretypes.h>

#include <vector>
#include <string>

namespace eurecar
{

/**
 * using driveworks, lane detection lcm definition
 *
 */
class dw_lane_detection
{
    public:
        int64_t    timestamp;

        int32_t    num_of_lanes;

        std::vector< std::string > lane_pos;

        std::vector< int32_t > max_y;

        std::vector< int32_t > min_y;

        std::vector< int32_t > coef_3;

        std::vector< int32_t > coef_2;

        std::vector< int32_t > coef_1;

        std::vector< int32_t > coef_0;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "dw_lane_detection"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int dw_lane_detection::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int dw_lane_detection::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int dw_lane_detection::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t dw_lane_detection::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* dw_lane_detection::getTypeName()
{
    return "dw_lane_detection";
}

int dw_lane_detection::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_of_lanes, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->num_of_lanes; a0++) {
        char* __cstr = const_cast<char*>(this->lane_pos[a0].c_str());
        tlen = __string_encode_array(
            buf, offset + pos, maxlen - pos, &__cstr, 1);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_of_lanes > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->max_y[0], this->num_of_lanes);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_of_lanes > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->min_y[0], this->num_of_lanes);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_of_lanes > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->coef_3[0], this->num_of_lanes);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_of_lanes > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->coef_2[0], this->num_of_lanes);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_of_lanes > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->coef_1[0], this->num_of_lanes);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_of_lanes > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->coef_0[0], this->num_of_lanes);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int dw_lane_detection::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_of_lanes, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->lane_pos.resize(this->num_of_lanes);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->num_of_lanes; a0++) {
        int32_t __elem_len;
        tlen = __int32_t_decode_array(
            buf, offset + pos, maxlen - pos, &__elem_len, 1);
        if(tlen < 0) return tlen; else pos += tlen;
        if(__elem_len > maxlen - pos) return -1;
        this->lane_pos[a0].assign(static_cast<const char*>(buf) + offset + pos, __elem_len -  1);
        pos += __elem_len;
    }

    if(this->num_of_lanes) {
        this->max_y.resize(this->num_of_lanes);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->max_y[0], this->num_of_lanes);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_of_lanes) {
        this->min_y.resize(this->num_of_lanes);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->min_y[0], this->num_of_lanes);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_of_lanes) {
        this->coef_3.resize(this->num_of_lanes);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->coef_3[0], this->num_of_lanes);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_of_lanes) {
        this->coef_2.resize(this->num_of_lanes);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->coef_2[0], this->num_of_lanes);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_of_lanes) {
        this->coef_1.resize(this->num_of_lanes);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->coef_1[0], this->num_of_lanes);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_of_lanes) {
        this->coef_0.resize(this->num_of_lanes);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->coef_0[0], this->num_of_lanes);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int dw_lane_detection::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_of_lanes; a0++) {
        enc_size += this->lane_pos[a0].size() + 4 + 1;
    }
    enc_size += __int32_t_encoded_array_size(NULL, this->num_of_lanes);
    enc_size += __int32_t_encoded_array_size(NULL, this->num_of_lanes);
    enc_size += __int32_t_encoded_array_size(NULL, this->num_of_lanes);
    enc_size += __int32_t_encoded_array_size(NULL, this->num_of_lanes);
    enc_size += __int32_t_encoded_array_size(NULL, this->num_of_lanes);
    enc_size += __int32_t_encoded_array_size(NULL, this->num_of_lanes);
    return enc_size;
}

uint64_t dw_lane_detection::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0x30e57ebcde98e3fcLL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
