/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __eurecar_dw_object_detection_hpp__
#define __eurecar_dw_object_detection_hpp__

#include <lcm/lcm_coretypes.h>

#include <vector>

namespace eurecar
{

/**
 * using driveworks, object detection lcm definition
 *
 */
class dw_object_detection
{
    public:
        int64_t    timestamp;

        int32_t    num_of_objects;

        std::vector< int32_t > type;

        std::vector< int32_t > lefttop_x;

        std::vector< int32_t > lefttop_y;

        std::vector< int32_t > obj_width;

        std::vector< int32_t > obj_height;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "dw_object_detection"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int dw_object_detection::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int dw_object_detection::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int dw_object_detection::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t dw_object_detection::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* dw_object_detection::getTypeName()
{
    return "dw_object_detection";
}

int dw_object_detection::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_of_objects, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->num_of_objects > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->type[0], this->num_of_objects);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_of_objects > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->lefttop_x[0], this->num_of_objects);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_of_objects > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->lefttop_y[0], this->num_of_objects);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_of_objects > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->obj_width[0], this->num_of_objects);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_of_objects > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->obj_height[0], this->num_of_objects);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int dw_object_detection::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_of_objects, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->num_of_objects) {
        this->type.resize(this->num_of_objects);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->type[0], this->num_of_objects);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_of_objects) {
        this->lefttop_x.resize(this->num_of_objects);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->lefttop_x[0], this->num_of_objects);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_of_objects) {
        this->lefttop_y.resize(this->num_of_objects);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->lefttop_y[0], this->num_of_objects);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_of_objects) {
        this->obj_width.resize(this->num_of_objects);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->obj_width[0], this->num_of_objects);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_of_objects) {
        this->obj_height.resize(this->num_of_objects);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->obj_height[0], this->num_of_objects);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int dw_object_detection::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, this->num_of_objects);
    enc_size += __int32_t_encoded_array_size(NULL, this->num_of_objects);
    enc_size += __int32_t_encoded_array_size(NULL, this->num_of_objects);
    enc_size += __int32_t_encoded_array_size(NULL, this->num_of_objects);
    enc_size += __int32_t_encoded_array_size(NULL, this->num_of_objects);
    return enc_size;
}

uint64_t dw_object_detection::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0xc60b96d3580f9537LL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
